name: $(date:yyyyMMdd)$(rev:.r)-$(SourceBranchName)

trigger:
- master

pool:
  name: NBS-MC-NEL-SC-DEV-BUILD

variables:
  azureSubscriptionEndpoint: NEL-SPN
  azureContainerRegistry: jssproxy1975.azurecr.io
  imageName: $(azureContainerRegistry)/gatsby-starter-netlify-cms:$(Build.BuildNumber)

steps:
- script: |
    set -e

    echo "Image: $IMAGENAME"
  displayName: Build site

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    node --version
    npm -v
    npm install
    npm run build
  displayName: 'yarn install and build'

- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)

- script: |
    set -e

    echo "Building $IMAGENAME..."
    docker build -t $IMAGENAME .
    docker push $IMAGENAME
  displayName: Build site

- task: AzureWebAppContainer@1
  displayName: Azure Web App on Container Deploy
  inputs:
    appName: gatsby-netlify-cms
    azureSubscription: $(azureSubscriptionEndpoint)
    imageName: $(imageName)